services:
  backend:
    image: nestjs/backend
    ports:
      - 4000:3000
    build:
      context: .
      dockerfile: Dockerfile.dev
    expose:
      - 4000
    volumes:
      - ./src:/usr/src/app/src
    command: ['yarn', 'start:dev']
  db:
    image: postgres:14.11
    environment:
      TZ: 'Asia/Tokyo'
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: todo
    ports:
      - 5432:5432
